minimum_pre_commit_version: 2.9.3
default_language_version:
  # Force all unspecified python hooks to run python3
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - name: Block commits to master
        id: no-commit-to-branch
      - name: Trim trailing whitespaces
        id: trailing-whitespace
      - name: Add empty line to end of file
        id: end-of-file-fixer
      - name: Check that exectuables have shebangs
        id: check-executables-have-shebangs
      - name: Check XML
        id: check-xml
      - name: Check JSON
        id: check-json
      - name: Check YAML
        id: check-yaml
        args: [ --allow-multiple-documents ]
      - name: Check that no large files were added (>500kB)
        id: check-added-large-files
        args: [ "--maxkb=500" ]

  - repo: https://github.com/google/yapf
    rev: v0.31.0
    hooks:
      - name: Run yapf
        id: yapf

  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - name: Run pylint
        id: pylint

  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
      - name: Run clang-format
        id: clang-format
        args: [ -style=file ]
      - name: Run cpplint
        id: cpplint
        args: [ "--filter=-legal/copyright,-build/include_order" ]
      - name: Run cppcheck
        id: cppcheck
        args: [ --std=c++17, --language=c++, --force, --quiet,
                "--enable=performance,portability",
                --library=googletest, --library=ci/cppcheck/gazebo,
                "--suppress=syntaxError:*test/src/*/test_*.cc" ]

  - repo: local
    hooks:
      - name: Lint package manifests
        id: xmllint
        entry: xmllint --noout
        language: system
        types: [ file ]
        files: (package.xml)$
        args: [ --schema, ci/xml_schemas/package_format2.xsd ]
      - name: Lint launch files
        id: xmllint
        entry: xmllint --noout
        language: system
        types: [ file ]
        files: \.(launch)$
        args: [ --schema, ci/xml_schemas/roslaunch.xsd ]
      - name: Lint URDF files
        id: xmllint
        entry: xmllint --noout
        language: system
        types: [ file ]
        files: \.(urdf)$
        args: [ --schema, ci/xml_schemas/package_format2.xsd ]
    # - name: Lint SDF files
    #   id: xmllint
    #   entry: xmllint --noout
    #   language: system
    #   types: [ file ]
    #   files: \.(sdf|model|world)$
    #   args: [ --schema, ci/xml_schemas/sdf.xsd ]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - name: Run cmake-format
        id: cmake-format
        additional_dependencies: [ pyyaml>=5.1 ]
      - name: Run cmake-lint
        id: cmake-lint
        additional_dependencies: [ pyyaml>=5.1 ]
