minimum_pre_commit_version: 2.9.3
default_language_version:
  # Force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespaces
      - id: end-of-file-fixer
        name: Add empty line to end of file
      - id: check-executables-have-shebangs
        name: Check that exectuables have shebangs
      - id: check-json
        name: Check JSON
      - id: check-yaml
        name: Check YAML
        args: [ --allow-multiple-documents ]
      - id: no-commit-to-branch
        name: Block commits to master
      - id: check-added-large-files
        name: Check large files (>500kB)
        args: [ "--maxkb=500" ]
  - repo: https://github.com/google/yapf
    rev: v0.31.0
    hooks:
      - id: yapf
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
      - id: clang-format
        args: [ -style=file ]
      - id: cpplint
        args: [ "--filter=-legal/copyright,-build/include_order" ]
      - id: cppcheck
        args: [ --std=c++17, --language=c++, --force, --quiet,
                "--enable=performance,portability",
                --library=googletest, --library=ci/cppcheck/gazebo,
                "--suppress=syntaxError:*test/src/*/test_*.cc"
              ]
