general:
  world_frame: "odom"
  publish_performance_stats: false

map:
  pruning_period: { seconds: 10.0 }
  visualization_period: { seconds: 10.0 }
  autosave_period: { seconds: -1.0 }
  autosave_path: ""
  data_structure:
    type: "wavelet_octree"
    min_cell_width: &min_cell_width { meters: 0.05 }
    max_height: 14

integrator:
  - input:
      type: "depth_image"
      topic_name: "/os1_cloud_node/points"
      topic_queue_length: 10
      max_wait_for_pose: { seconds: 1.0 }
    integration_method:
      type: "coarse_to_fine_wavelet_integrator"
      min_range: { meters: 1.0 }
      max_range: { meters: 6.0 }
      max_acceptable_update_error: 0.1
      max_update_resolution: *min_cell_width
    projection_model:
      type: "pinhole_camera_projector"
      width: 848
      height: 480
      fx: 421.4140625
      fy: 421.4140625
      cx: 429.63104248046875
      cy: 240.18775939941406
    measurement_model:
      type: "continuous_volumetric_log_odds"
      angle_sigma: { degrees: 0.04 }
      range_sigma: { meters: 0.04 }
      scaling_free: 0.2
      scaling_occupied: 0.4
