name: 'Setup ccache'
description: 'Install ccache and configure it to use GitHub cache sharing'

runs:
  using: "composite"
  steps:
    - name: Install and configure ccache
      shell: bash
      run: |
        apt-get update && apt-get install -y ccache
        echo "PATH="/usr/lib/ccache:$PATH"" >> $GITHUB_ENV
        mkdir -p $CCACHE_DIR
        ccache --max-size=1G
        echo "CCACHE_STAMP=$(date +%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV

    - name: Setup ccache cache sharing
      uses: actions/cache@v2
      with:
        path: ${{env.CCACHE_DIR}}
        key: noetic-ccache-${{env.CCACHE_STAMP}}
        restore-keys: noetic-ccache-
