name: Build test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal

    steps:
      - name: Environment info
        run: |
          pwd
          uname -r
          lsb_release -a

      - name: Install general and ROS-related APT packages
        run: |
          apt-get update
          apt-get install -y git tree python3-catkin-tools python3-vcstool

      - name: Fetch the package's code
        uses: actions/checkout@v2
        with:
          path: catkin_ws/src/wavemap_2d

      - name: Install package dependencies
        working-directory: catkin_ws
        shell: bash
        run: |
          vcs import --recursive --input src/wavemap_2d/wavemap_2d_https.yml src
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Show the workspace tree
        working-directory: catkin_ws
        run: tree

      - name: Build in release mode
        working-directory: catkin_ws
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          catkin init
          catkin build wavemap_2d -j$(nproc) -l$(nproc) --no-status --force-color --cmake-args -DCMAKE_BUILD_TYPE=Release
