name: Build test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

# NOTE: We do not store the catkin_ws under $HOME ("/github/home/") since that
#       dir persists between jobs when using self-hosted GitHub Actions runners
#       (/github/home is a docker volume mapped to the container's host).
env:
  CATKIN_WS_PATH: '/home/ci/catkin_ws'

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal

    steps:
      - name: Environment info
        run: uname -r && lsb_release -a

      - name: Install general and ROS-related APT packages
        run: |
          apt-get update
          apt-get install -y git tree python3-catkin-tools python3-vcstool

      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Create catkin_ws and install package dependencies
        shell: bash
        run: |
          mkdir -p ${{env.CATKIN_WS_PATH}}/src
          cd ${{env.CATKIN_WS_PATH}}
          ln -s $GITHUB_WORKSPACE src
          echo "::group::Import from-source dependencies with vcstool"
          vcs import --recursive --input src/wavemap_2d/wavemap_2d_https.yml src
          echo "::endgroup::"
          echo "::group::Install system dependencies with rosdep"
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          echo "::endgroup::"

      # TODO(victorr): Fix this upstream
      - name: Manually install opencv_viz (missing opencv3 dependency)
        run: apt-get install -y libopencv-viz-dev

      - name: Show the workspace tree
        working-directory: ${{env.CATKIN_WS_PATH}}
        run: pwd && tree -l

      - name: Build in release mode
        working-directory: ${{env.CATKIN_WS_PATH}}
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          catkin init
          catkin build wavemap_2d --no-status --force-color --cmake-args -DCMAKE_BUILD_TYPE=Release
