name: Build test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    container: ros:noetic-ros-base-focal
    steps:
      - uses: actions/checkout@v2
      - name: Install catkin-tools
        run: apt update && apt install -y python3-catkin-tools
