name: Continuous Integration

on:
  push:
    branches: [ $default-branch ]
  pull_request:

# NOTE: We do not store the work files under $HOME ("/github/home/") since that
#       dir persists between jobs when using self-hosted GitHub Actions runners
#       (/github/home is a docker volume mapped to the container's host).
env:
  CATKIN_WS_PATH: '/home/ci/catkin_ws'
  CCACHE_DIR: '/home/ci/ccache'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps

      - name: Build in release mode
        working-directory: ${{env.CATKIN_WS_PATH}}
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          catkin init
          catkin build wavemap_2d --no-status --force-color --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats

  test:
    name: Test
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps

      - name: Build and run unit tests
        working-directory: ${{env.CATKIN_WS_PATH}}
        shell: bash
        run: |
          echo "::group::Build unit tests"
          catkin build wavemap_2d --no-status --force-color --no-deps --verbose --catkin-make-args tests
          echo "::endgroup::"
          echo "::group::Run unit tests"
          all_tests_passed=1
          for f in devel/lib/wavemap_2d/test_*
            do $f --gtest_color=yes || all_tests_passed=0
          done
          if [ $all_tests_passed -ne 1 ]; then 
            echo "Not all tests passed!"
            exit 1
          fi
          echo "::endgroup::"

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats

  coverage:
    name: Coverage
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps

      - name: Build in debug mode
        working-directory: ${{env.CATKIN_WS_PATH}}
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          catkin config --cmake-args -DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
          catkin build wavemap_2d --no-status --force-color

      - name: Analyze unit test coverage
        working-directory: ${{env.CATKIN_WS_PATH}}
        shell: bash
        run: |
          catkin build wavemap_2d -v --no-status --force-color --no-deps --catkin-make-args wavemap_2d_coverage_report

      - name: Upload coverage stats to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{env.CATKIN_WS_PATH}}/build/wavemap_2d
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats
