name: Continuous Integration

on:
  push:
    branches: [ $default-branch ]
  pull_request:

# NOTE: We do not store the work files under $HOME ("/github/home/") since that
#       dir persists between jobs when using self-hosted GitHub Actions runners
#       (/github/home is a docker volume mapped to the container's host).
env:
  CATKIN_WS_PATH: '/home/ci/catkin_ws'
  CCACHE_DIR: '/home/ci/ccache'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache
        with:
          cache-key: noetic-gcc-release

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps

      - name: Build in release mode
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: catkin build wavemap_2d --no-status --force-color

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats

  pre-commit:
    name: Lint
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Install pre-commit's dependencies
        run: |
          apt-get update
          apt-get install -y git python3-pip clang-format
          pip3 install pre-commit cpplint

      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Run the pre-commit hooks
        run: pre-commit run --all-files

  test:
    name: Test
    needs: build
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache
        with:
          cache-key: noetic-gcc-release

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps

      - name: Build unit tests
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: |
          catkin build wavemap_2d --no-status --force-color
          catkin build wavemap_2d --no-status --force-color --no-deps --verbose --catkin-make-args tests

      - name: Run unit tests
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: |
          all_tests_passed=1
          for f in devel/lib/wavemap_2d/test_*
            do $f --gtest_color=yes || all_tests_passed=0
          done
          if [ $all_tests_passed -ne 1 ]; then
            echo "Not all tests passed!"
            exit 1
          fi

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats

  coverage:
    name: Coverage
    needs: test
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache
        with:
          cache-key: noetic-gcc-debug

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps
        with:
          catkin-config-args: --cmake-args -DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build in debug mode
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: catkin build wavemap_2d --no-status --force-color

      - name: Analyze unit test coverage
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: |
          catkin build wavemap_2d -v --no-status --force-color --no-deps --catkin-make-args wavemap_2d_coverage_report

      - name: Upload coverage stats to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ env.CATKIN_WS_PATH }}/build/wavemap_2d
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats

  sanitize:
    name: Sanitize ${{ matrix.sanitizer.detects }}
    strategy:
      matrix:
        sanitizer:
          - { name: UBSAN, detects: 'undefined behavior' }
          - { name: ASAN, detects: 'addressability and leaks' }
          - { name: TSAN, detects: 'data races and deadlocks' }
          # NOTE: MSAN is not used for now since it also requires all deps to be
          #       instrumented (recompiled with clang and the MSan flags, LLVM's
          #       stdlib instead of GCCs,...). We therefore use Valgrind to
          #       check for uninitialized memory usage errors instead.
      fail-fast: false
    needs: test
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache
        with:
          cache-key: noetic-gcc-${{ matrix.sanitizer.name }}

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps
        with:
          catkin-config-args: --cmake-args -DCMAKE_BUILD_TYPE=Release -DUSE_${{ matrix.sanitizer.name }}=ON

      - name: Build unit tests
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: |
          catkin build wavemap_2d --no-status --force-color
          catkin build wavemap_2d --no-status --force-color --no-deps --verbose --catkin-make-args tests

      - name: Check unit tests with ${{ matrix.sanitizer.name }}
        working-directory: ${{ env.CATKIN_WS_PATH }}
        env:
          UBSAN_OPTIONS: halt_on_error=1:print_stacktrace=1
          ASAN_OPTIONS: halt_on_error=1:detect_leaks=1:detect_stack_use_after_return=1
          TSAN_OPTIONS: halt_on_error=1
        shell: bash
        run: |
          all_tests_passed=1
          for f in devel/lib/wavemap_2d/test_*
            do $f --gtest_color=yes || all_tests_passed=0
          done
          if [ $all_tests_passed -ne 1 ]; then
            echo "Not all tests passed!"
            exit 1
          fi

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats

  valgrind:
    name: Valgrind memcheck
    needs: test
    runs-on: self-hosted
    container:
      image: ros:noetic-ros-base-focal
    steps:
      - name: Fetch the package's code
        uses: actions/checkout@v2

      - name: Setup ccache
        uses: ./.github/actions/setup-ccache
        with:
          cache-key: noetic-gcc-release

      - name: Setup catkin_ws and install all dependencies
        uses: ./.github/actions/setup-catkin-ws-and-install-deps
        with:
          catkin-config-args: --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Install Valgrind
        run: apt-get install -y valgrind

      - name: Build unit tests
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: |
          catkin build wavemap_2d --no-status --force-color
          catkin build wavemap_2d --no-status --force-color --no-deps --verbose --catkin-make-args tests

      - name: Check unit tests with Valgrind memcheck
        working-directory: ${{ env.CATKIN_WS_PATH }}
        shell: bash
        run: |
          all_tests_passed=1
          for f in devel/lib/wavemap_2d/test_*
            do valgrind --exit-on-first-error=yes --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=definite,indirect,possible $f --gtest_color=yes || all_tests_passed=0
          done
          if [ $all_tests_passed -ne 1 ]; then
            echo "Not all tests passed!"
            exit 1
          fi

      - name: Show statistics for ccache
        uses: ./.github/actions/log-ccache-stats
