name: 'Log ccache stats'
description: 'Log statistics for ccache if it was enabled'

runs:
  using: "composite"
  steps:
    - name: Ccache statistics
      shell: bash
      run: |
        if [ "$(which gcc)" == "/usr/lib/ccache/gcc" ]; then
          echo "Using ccache: true"
          echo "Ccache stats"
          ccache --show-stats
        else
          echo "Using ccache: FALSE"
        fi
